language: java
jdk: oraclejdk8
install: true
deploy:
  provider: releases
  api_key: c66228ffa840dfdb3937d5cb59fbdb4667d00d5c
  file: target/release-1.0-SNAPSHOT.jar
  on:
    repo: yogonza524/release-ci
