language: java

jdk: oraclejdk8
install: true

deploy:
  provider: releases
  api_key: "987b96f648ebb6dc8f6f4b857e20a106a4fb8483"
  file: "target/release-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
